document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('form-cadastro');const submitButton=document.getElementById('btn-enviar');const cpfInput=document.getElementById('cpf');const telefoneInput=document.getElementById('telefone');const cepInput=document.getElementById('cep');const nomeInput=document.getElementById('nome');const emailInput=document.getElementById('email');const enderecoInput=document.getElementById('endereco');const cidadeInput=document.getElementById('cidade');const estadoInput=document.getElementById('estado');const tagsContainer=document.getElementById('tags-interesses');const allTags=tagsContainer.querySelectorAll('.tag');const formAlert=document.getElementById('form-alert');const modal=document.getElementById('modal-confirmacao');const modalConfirmBtn=document.getElementById('modal-botao-confirmar');const modalCancelBtn=document.getElementById('modal-botao-cancelar');const toast=document.getElementById('form-toast');const statusContainer=document.getElementById('status-candidato');const badgeElement=document.getElementById('badge-tipo-membro');const allInputs=[nomeInput,emailInput,cpfInput,telefoneInput,cepInput,enderecoInput,cidadeInput,estadoInput];function showError(input,message){const formGroup=input.parentElement;formGroup.classList.remove('success');formGroup.classList.add('error');const errorMessage=formGroup.querySelector('.validation-message');errorMessage.textContent=message;input.setAttribute('aria-invalid','true')}
function showSuccess(input){const formGroup=input.parentElement;formGroup.classList.remove('error');formGroup.classList.add('success');const errorMessage=formGroup.querySelector('.validation-message');errorMessage.textContent='';input.setAttribute('aria-invalid','false')}
function clearValidation(input){const formGroup=input.parentElement;formGroup.classList.remove('error');formGroup.classList.remove('success');const errorMessage=formGroup.querySelector('.validation-message');errorMessage.textContent='';input.removeAttribute('aria-invalid')}
function showModal(){modal.style.display='flex';setTimeout(()=>modal.classList.add('show'),10);modalCancelBtn.focus()}
function hideModal(){modal.classList.remove('show');setTimeout(()=>{modal.style.display='none';submitButton.focus()},300)}
function showToast(){toast.style.display='block';setTimeout(()=>toast.classList.add('show'),10);setTimeout(()=>{toast.classList.remove('show');setTimeout(()=>toast.style.display='none',400)},3000)}
function updateBadgeStatus(){const selectedTags=tagsContainer.querySelectorAll('.tag.selected');let isMusico=!1;let isApoio=!1;selectedTags.forEach(tag=>{const valor=tag.dataset.valor;if(['percussao','sopros','corpo-coreografico','bandeiras'].includes(valor)){isMusico=!0}
if(valor==='logistica'){isApoio=!0}});if(isMusico){badgeElement.textContent="Músico/Artista";badgeElement.className="badge";statusContainer.style.display="block"}else if(isApoio){badgeElement.textContent="Voluntário/Apoio";badgeElement.className="badge badge-apoio";statusContainer.style.display="block"}else{statusContainer.style.display="none"}}
function validateNome(){if(nomeInput.value.trim()==="")return showError(nomeInput,'Nome completo é obrigatório.');if(nomeInput.value.trim().split(' ').length<2)return showError(nomeInput,'Por favor, digite nome e sobrenome.');return showSuccess(nomeInput)}
function validateEmail(){const re=/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/;if(emailInput.value.trim()==="")return showError(emailInput,'Email é obrigatório.');if(!re.test(String(emailInput.value).toLowerCase()))return showError(emailInput,'Formato de email inválido.');return showSuccess(emailInput)}
function validateCpf(){if(cpfInput.value.trim()==="")return showError(cpfInput,'CPF obrigatório.');if(cpfInput.value.length<14)return showError(cpfInput,'CPF incompleto. Formato: 000.000.000-00');return showSuccess(cpfInput)}
function validateTelefone(){if(telefoneInput.value.trim()==="")return showError(telefoneInput,'Telefone obrigatório.');if(telefoneInput.value.length<15)return showError(telefoneInput,'Telefone incompleto. Formato: (00) 00000-0000');return showSuccess(telefoneInput)}
function validateCep(){if(cepInput.value.trim()==="")return showError(cepInput,'CEP obrigatório.');if(cepInput.value.length<9)return showError(cepInput,'CEP incompleto. Formato: 00000-000');return showSuccess(cepInput)}
function validateRequiredText(input){if(input.value.trim()==="")return showError(input,'Este campo é obrigatório.');return showSuccess(input)}
function validateTags(){const selectedTags=tagsContainer.querySelectorAll('.tag.selected').length;const tagsErrorEl=tagsContainer.nextElementSibling;const tagsFormGroup=tagsContainer.parentElement;if(selectedTags===0){tagsFormGroup.classList.add('error');tagsFormGroup.classList.remove('success');tagsErrorEl.textContent='Selecione pelo menos um interesse.';return!1}else{tagsFormGroup.classList.remove('error');tagsFormGroup.classList.add('success');tagsErrorEl.textContent='';return!0}}
function checkButtonState(){const cpfValido=cpfInput.value.length===14;const telefoneValido=telefoneInput.value.length===15;const cepValido=cepInput.value.length===9;const nomeValido=nomeInput.value.trim()!==""&&nomeInput.value.trim().split(' ').length>=2;const emailValido=emailInput.value.includes('@')&&/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/.test(emailInput.value);const enderecoValido=enderecoInput.value.trim()!=="";const cidadeValido=cidadeInput.value.trim()!=="";const estadoValido=estadoInput.value.trim()!=="";const tagsValidas=tagsContainer.querySelectorAll('.tag.selected').length>0;if(cpfValido&&telefoneValido&&cepValido&&nomeValido&&emailValido&&enderecoValido&&cidadeValido&&estadoValido&&tagsValidas){submitButton.disabled=!1}else{submitButton.disabled=!0}}
cpfInput.addEventListener('input',(e)=>{let value=e.target.value.replace(/\D/g,'');value=value.replace(/(\d{3})(\d)/,'$1.$2');value=value.replace(/(\d{3})(\d)/,'$1.$2');value=value.replace(/(\d{3})(\d{1,2})$/,'$1-$2');e.target.value=value;checkButtonState()});telefoneInput.addEventListener('input',(e)=>{let value=e.target.value.replace(/\D/g,'');value=value.replace(/^(\d{2})(\d)/g,'($1) $2');value=value.replace(/(\d{5})(\d)/,'$1-$2');e.target.value=value;checkButtonState()});cepInput.addEventListener('input',(e)=>{let value=e.target.value.replace(/\D/g,'');value=value.replace(/^(\d{5})(\d)/,'$1-$2');e.target.value=value;checkButtonState()});nomeInput.addEventListener('input',checkButtonState);emailInput.addEventListener('input',checkButtonState);enderecoInput.addEventListener('input',checkButtonState);cidadeInput.addEventListener('input',checkButtonState);estadoInput.addEventListener('input',checkButtonState);nomeInput.addEventListener('blur',validateNome);emailInput.addEventListener('blur',validateEmail);cpfInput.addEventListener('blur',validateCpf);telefoneInput.addEventListener('blur',validateTelefone);cepInput.addEventListener('blur',validateCep);enderecoInput.addEventListener('blur',()=>validateRequiredText(enderecoInput));cidadeInput.addEventListener('blur',()=>validateRequiredText(cidadeInput));estadoInput.addEventListener('blur',()=>validateRequiredText(estadoInput));allTags.forEach(tag=>{tag.addEventListener('click',()=>{tag.classList.toggle('selected');const isSelected=tag.classList.contains('selected');tag.setAttribute('aria-checked',isSelected?'true':'false');checkButtonState();validateTags();updateBadgeStatus()});tag.addEventListener('keydown',(e)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();tag.click()}})});form.addEventListener('submit',(e)=>{e.preventDefault();validateNome();validateEmail();validateCpf();validateTelefone();validateCep();validateRequiredText(enderecoInput);validateRequiredText(cidadeInput);validateRequiredText(estadoInput);validateTags();checkButtonState();if(!submitButton.disabled){formAlert.style.display='none';showModal()}else{formAlert.textContent='Por favor, corrija os erros no formulário antes de enviar.';formAlert.style.display='block'}});modalCancelBtn.addEventListener('click',hideModal);modalConfirmBtn.addEventListener('click',()=>{hideModal();console.log('Formulário enviado com sucesso!');form.reset();allTags.forEach(tag=>tag.classList.remove('selected'));allInputs.forEach(clearValidation);const tagsFormGroup=tagsContainer.parentElement;tagsFormGroup.classList.remove('success','error');tagsFormGroup.querySelector('.validation-message').textContent='';statusContainer.style.display='none';submitButton.disabled=!0;showToast()});document.addEventListener('keydown',(e)=>{if(!modal.classList.contains('show')){return}
if(e.key==='Escape'){e.preventDefault();hideModal()}
if(e.key==='Tab'){const focusableElements=[modalCancelBtn,modalConfirmBtn];const firstElement=focusableElements[0];const lastElement=focusableElements[1];if(e.shiftKey){if(document.activeElement===firstElement){e.preventDefault();lastElement.focus()}}else{if(document.activeElement===lastElement){e.preventDefault();firstElement.focus()}}}});checkButtonState()})