document.addEventListener('DOMContentLoaded',()=>{const mainContent=document.getElementById('main-content');const updateActiveNav=(path)=>{const navLinks=document.querySelectorAll('.nav-link');const ctaButton=document.querySelector('.cta-button');navLinks.forEach(link=>link.classList.remove('active'));if(ctaButton){ctaButton.classList.remove('active')}
if(path.includes('cadastro.html')){if(ctaButton)ctaButton.classList.add('active');}else if(path==='/'||path.includes('index.html')){const homeLink=document.querySelector('.nav-link[href="index.html"]');if(homeLink)homeLink.classList.add('active');}else{const activeLink=Array.from(navLinks).find(link=>{const href=link.getAttribute('href');return path.includes(href)});if(activeLink){activeLink.classList.add('active')}}};const loadPage=async(url,updateHistory=!0,scrollToTop=!0)=>{try{mainContent.style.opacity='0.5';const response=await fetch(url);const htmlText=await response.text();const parser=new DOMParser();const doc=parser.parseFromString(htmlText,'text/html');const newContent=doc.getElementById('main-content').innerHTML;const newTitle=doc.querySelector('title').innerText;mainContent.innerHTML=newContent;document.title=newTitle;if(url.includes('membros.html')){renderizarPaginaMembros()}
if(scrollToTop){window.scrollTo(0,0)}
mainContent.style.opacity='1';updateActiveNav(url);const urlObject=new URL(url,window.location.origin);const hash=urlObject.hash;if(hash){const elementId=hash.substring(1);setTimeout(()=>{const targetElement=document.getElementById(elementId);if(targetElement){console.log('Hash encontrado, rolando para:',elementId);const header=document.querySelector('.main-header');const headerHeight=header?header.offsetHeight:0;const elementPosition=targetElement.getBoundingClientRect().top;const offsetPosition=elementPosition+window.pageYOffset-headerHeight-20;window.scrollTo({top:offsetPosition,behavior:"smooth"})}else{console.warn('Elemento com ID',elementId,'não encontrado para rolar.')}},0)}
if(updateHistory){history.pushState({path:url},newTitle,url)}}catch(error){console.error('Erro ao carregar a página:',error);window.location.href=url}};document.body.addEventListener('click',(e)=>{const link=e.target.closest('a');if(!link||link.target==='_blank'){return}
if(link.pathname===window.location.pathname&&link.hash){return}
if(link.hostname!==window.location.hostname){return}
if(link.pathname.includes('cadastro.html')){console.log('Navegando para Cadastro (full load), recarregamento completo.');return}
e.preventDefault();loadPage(link.href,!0,!0)});window.addEventListener('popstate',(e)=>{loadPage(window.location.pathname,!1,!1)});const currentPath=window.location.pathname;if(currentPath.includes('membros.html')){renderizarPaginaMembros()}
updateActiveNav(currentPath)})